project:
  type: book
  output-dir: docs
  preview:
    port: 4321

date: today
date-modified: last-modified
date-format: "Do MMMM YYYY"  

book:
  title: "Antibiotic augmentation of allograft bone"
  # subtitle: "ample alliteration always assists accurate apprehension"
  output-file: thesis_Day_2026
  description: |
    Thesis of a postgraduate research project being conducted at the University of Western Australia under the supervision of [Professor Kermit T. Frog](https://www.ed.ac.uk/profile/kermit) and [Dr. G. O'Nzo](https://www.ed.ac.uk/profile/gonzo). 
  author: 
    name: "Robert Edward Day"
    affiliations:
      - name: University of Western Australia
        department: School of Medicine
        group: Biomedical Engineering
    degrees:
    - BMechEng (SAIT)
    - MBiomedEng (UNSW)
    orcid: 0000-0003-3442-2298

  chapters:
    # -------------------------------------------------------------------
    # title page, abstract, lay summary, declaration, preface, acknowledgements, 
    # table of contents, list of tables, list of figures, abbreviations; 
    # the body of the thesis; references; 
    # and finally appendices.
    # -------------------------------------------------------------------
    - index.qmd # contains the (placeholder) abstract and the _preface.qmd
    # declaration, dedication, and acknowledgements in _front-matter.qmd, 
    # to be included from index.qmd
    # table of contents (and lists of tables and figures) included in index.qmd
    - 10-introduction.qmd
    - 20-conceptual-framework.qmd
    - 30-method.qmd
    - 40-discussion.qmd
    - 50-conclusion.qmd
    - references.qmd
    # appendices: 
    # 
  sidebar:
    contents: auto
    style: docked
    collapse-level: 2
  page-footer: 
    left: "What a lovely day." 

bibliography: thesis.bib
# csl: /path/to/your/style-file.csl
csl: chicago-author-date-with-ibid.csl

# Details to be added to the title page
degreetype: Doctor of Philosophy
submitted: 2026
school: School of Medicine
discipline: Biomedical Engineering

format:
  html:
    theme: 
    - spacelab
    fontsize: 12pt
    page-layout: article
    fig-cap-location: bottom
    citation-location: document
    toc: false
    toc-depth: 3
    toc-expand: true
    toc-title: On this page
    number-sections: true
    number-depth: 2

  pdf: 
    documentclass: scrbook
    keep-tex: true
    papersize: a4
    include-in-header: include-in-header.tex
    template-partials: 
      - before-body.tex
      - toc.tex
    geometry:
      - inner=3cm
      - outer=4cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    lof: true
    lot: true

    # supervisor: 
    #   - name: "Professor Kermit T. Frog"
    #     affiliation: University of Edinburgh
    #   - name: "Dr. G. O'Nzo"
    #     affiliation: University of Edinburgh
    # examiner: 
    #   - name: "TBD"
    #     affiliation: TBD
    #   - name: "TBD"
    #     affiliation: TBD

    indent: false
    linestretch: 1.25
    fontsize: 12pt
    pdf-engine: xelatex
    # You can use any font installed on your computer.
    # mainfont: "Georgia"
    # sansfont: "Optima"
    # monofont: "Courier New"
    # mathfont: "TeX Gyre Termes Math"
    link-citations: true
